In [57]:
#%matplotlib inline
import numpy as np
from numpy import mat
#from pylab import *
#import matplotlib
#import matplotlib.pyplot as plt

        
    
    
    #回带

#homework_02_01
A = np.random.randint(0,256,size = (4,4))
B = np.pad(A,((1,1),(1,1)),'constant')

#homework_02_02
C = np.random.randint(0,256,size = (5,5))
C[4,:4] = range(1,5)

#homework_02_03
D = np.zeros((8,8))
for i in range(D.shape[0]):
    for j in range(D.shape[1]):
        if (i+j) % 2 == 1:
            D[i,j] = 1

#homework_02_04
E = [[3., 4., 2.],
     [5., 3., 4.],
     [8., 2., 7.]]
F = [[10],
     [14],
     [20]]
x = mat(E).I*mat(F)

#homework_02_05
G = np.random.randint(0,256,size = (8))
H = G.tolist()
H.reverse()
#print(H)

#homework_02_06
I = np.random.randint(0,256,size = (10,10))
IMax = np.max(I)
IMin = np.min(I)


255 9 [[167 117  92 142 114 167 181 180 169 102]
 [198 172  21 153  34  69 123 122 162 167]
 [129  29 129 103 172 102 142  58 166  61]
 [175  19 168  11  20  18  86 135 225 109]
 [156 157  87  83 167 117  81 193  76  96]
 [ 94  12 249 176  15 148 233  22  90 157]
 [162 189  99 114   9  77 202 127 255  23]
 [ 26  72 239 127 110  25 167 224 246  15]
 [117 174 249 103  12 218 195 227 129 244]
 [ 39  75 141 127 198  83   9 106 142 167]]
